### ISSUE TITLE
 No external network access to the instances

### ISSUE THREAD

**Issue by gkatsaros** [stackanetes/stackanetes#156] opened 2017-03-18 08:51 UTC
Hi,
I have installed Stackanetes over a Tectonic Cluster and all look fine.
However, I cannot get the external (provider) network working:
I have defined an external network with the physnet1 flat network but I cannot get access from the external network to the VM instances.

Checking the ov configs I discovered that at the configs map openvswitch-ensure-configured.sh.yaml.j2 the command that actually bridges the physical port with the br-ex is commented out. 
Is that normal?
Does the current Stackanetes not offer external connectivity?

Is there a way to get the external network connectivity working?

Thank you very much in advance for any help.

**Comment by ss7pro** [comment] 2017-03-24 03:52
Unfortunately you need to setup ezternal connectivity on your own. This action needs to happen on all openstack control plane nodes.

**Comment by gkatsaros** [comment] 2017-03-24 11:34
Is there any complication or step that I should be careful? (I tried once to add the port to th ovs bridge manually but it broke the nova and libvirt pods etc.)

Is there any relevant reference or instructions that I could follow?

Thank you in advance.

**Comment by josefhernandez** [comment] 2017-03-24 11:56
I'm stuck at this point too

**Comment by ss7pro** [comment] 2017-03-25 22:00
To help you here I'll need few more questions answered:

- Do you have spare Ethernet interface in server ?
- Does your external network is delivered using tagged vlan ?

**Comment by josefhernandez** [comment] 2017-03-25 23:14
@ss7pro In my case:
yes, 2 spare ethernet interfaces
no, but i can change it if needed

is this the same scenario for you @gkatsaros ?

**Comment by gkatsaros** [comment] 2017-03-27 07:44
Its the same for me:
2 interfaces, one used as the management for the tectonic cluster and a spare 2nd interface (which could be used for Openstack's provider network). 
Traffic of the external network is based on a tagged vlan. 

Thx a lot for the help.

**Comment by ss7pro** [comment] 2017-03-27 09:55
@gkatsaros @josefhernandez So folks, we would go with dedicated interface configuration:

1) ensure that there're no ip addresses assigned to interface you're going to use:
ip addr show dev $INTERFACE_NAME  | egrep 'inet\s'
2) make sure interface is up
ip link show $INTERFACE_NAME
3) add port to br-ex bridge (needs to happen from vswitchd container)
ovs-vsctl --no-wait add-port br-ex $INTERFCE_NAME

4) create external network in neutron
** for native unattged vlan use NETWORK_TYPE=flat
**for tagged vlan use NETWORK_TYPE=vlan  and add --provider-segment $VLAN_NUMBER
openstack network create external --provider-network-type $NETWORK_TYPE --provider-physical-network physnet1


let me know if that works for you.

**Comment by PAStheLoD** [comment] 2017-03-27 10:09
Hello,

In theory using a setup with bonded interfaces with VLANs instead of separate NICs should work, right? (As [recommended](https://docs.openstack.org/project-deploy-guide/openstack-ansible/ocata/overview-requirements.html#network-recommendations) by the OpenStack Ansible deployment guide.) Bonding would provide link level HA+LB (LACP/802.3ad using balance-tcp mode, hopefully all via OVS.) And on top of all this Neutron's distributed virtual router could simply works as intended, no?

**Comment by josefhernandez** [comment] 2017-03-27 15:22
@ss7pro working for me ! fully functional openstack environment

suggestion: modify parameter.yaml to include the spare interface name and modify openswitchd command to automatically add port to br-ex bridge, based on configuration

what do you thing ?

**Comment by ss7pro** [comment] 2017-03-28 06:07
@PAStheLoD Yes, this setup would work as well.

**Comment by ss7pro** [comment] 2017-04-07 14:47
closing for now, pls repoen when needed again.

**Closed by ss7pro** 2017-04-07 14:47 UTC
